version: '3'

services:
  # postgres-db:
  #   image: "postgres:15.1-alpine"
  #   container_name: postgres-db
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
    # environment: db, user, pwd, etc

  backend:
    # depends_on:
    #   - postgres-db
      # we can use "links" instead of "depends_on" as well
    build: ./
    container_name: backend
    environment:
      - PORT:3001
      # youtube API key(s) as well
    ports:
      - 3001:3001

  frontend:
    depends_on:
      - backend
    build: ./client2
    container_name: frontend
    ports:
      - 3000:3000

# volumes:
#   db-data: